[package]
name = "aws-encryption-checker"
version = "0.1.0"
edition = "2021"
authors = ["Your Name <your.email@example.com>"]
description = "AWS service encryption configuration checker"
license = "MIT"
repository = "https://github.com/yourusername/aws-encryption-checker"

[dependencies]
aws-config = "1.0.1"
aws-sdk-s3 = "1.3.0"
aws-sdk-rds = "1.3.0"
aws-sdk-kms = "1.3.0"
aws-sdk-ebs = "1.3.0"
aws-sdk-ec2 = "1.3.0"
aws-sdk-dynamodb = "1.3.0"
aws-sdk-efs = "1.3.0"
aws-sdk-sns = "1.3.0"
aws-sdk-sqs = "1.3.0"
aws-sdk-lambda = "1.3.0"
aws-sdk-cloudtrail = "1.3.0"
aws-sdk-elasticsearch = "1.3.0"
aws-sdk-secretsmanager = "1.3.0"
aws-sdk-redshift = "1.3.0"
aws-sdk-backup = "1.3.0"
aws-sdk-glacier = "1.3.0"
aws-sdk-workspaces = "1.3.0"
aws-sdk-elasticache = "1.3.0"
aws-sdk-docdb = "1.3.0"
aws-sdk-neptune = "1.3.0"
clap = { version = "4.0", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }
futures = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
indicatif = "0.17"
chrono = { version = "0.4", features = ["serde"] }
tracing = "0.1"
tracing-subscriber = "0.3"